"use client";

import { FormEvent, useEffect, useState } from "react";

type Locale = "tr" | "en";
const heroSlides = [
  "/hero-hvac-facility.png",
  "/hero-hvac-diagnostics.png",
  "/hero-refrigerant-cycle.png",
  "/hero-global-logistics.png",
];

const copy = {
  tr: {
    nav: ["Vente", "Faaliyet Alanları", "Markalar", "Projeler", "İçgörüler", "İletişim"], eyebrow: "DIŞ TİCARET • DİSTRİBÜTÖRLÜK • İŞ GELİŞTİRME",
    hero: <>Ürünleri.<br />Üreticileri. <em>Pazarları.</em></>, lead: "Türkiye merkezli bir dış ticaret ve iş geliştirme şirketi olarak doğru ürünleri, güvenilir üreticileri ve yeni pazar fırsatlarını buluşturuyoruz.", discover: "Vente’yi keşfedin", areas: "Faaliyet alanlarımız", what: "NE YAPIYORUZ?", whatTitle: <>Tek yetkinlik.<br />Dört <em>iş alanı.</em></>, whatLead: "Ürün keşfinden dağıtıma, proje tedariğinden yeni pazar yapılanmasına kadar bütünsel ticari çözümler geliştiriyoruz.", tradeTitle: "İhtiyacı siz tanımlayın. Çözümü biz bulalım.", tradeText: "Başta Afrika olmak üzere farklı pazarlardaki müşterilerimiz için ürün araştırması, üretici seçimi, satın alma, konsolidasyon ve ihracat süreçlerini yönetiyoruz.", projectsTitle: <>İhtiyaçtan teslimata.<br /><em>Gerçek projeler.</em></>, brandsTitle: <>Teknoloji üreticileriyle<br /><em>güçlü ortaklıklar.</em></>, brandsText: "HVACR profesyonellerinin işlerini daha hızlı, doğru ve güvenli yapmalarını sağlayan yenilikçi markaları Türkiye pazarıyla buluşturuyoruz.", bdTitle: <>Bölgesel büyüme için<br /><em>yerel partneriniz.</em></>, aboutTitle: <>Yerel bilgi.<br /><em>Uluslararası erişim.</em></>, contactTitle: <>Doğru fırsatı<br /><em>birlikte geliştirelim.</em></>, submit: "Talebinizi gönderin",
  },
  en: {
    nav: ["Vente", "Business Areas", "Brands", "Projects", "Insights", "Contact"], eyebrow: "INTERNATIONAL TRADE • DISTRIBUTION • BUSINESS DEVELOPMENT",
    hero: <>Connecting Products.<br />Markets. <em>Opportunities.</em></>, lead: "Vente is a Türkiye-based international trade and business development company connecting innovative manufacturers, products and markets.", discover: "Discover Vente", areas: "Our business areas", what: "WHAT WE DO", whatTitle: <>One capability.<br />Four <em>business areas.</em></>, whatLead: "From product discovery and distribution to project supply and market development, we build integrated commercial solutions.", tradeTitle: "You define the need. We find the solution.", tradeText: "For clients across Africa and other international markets, we manage sourcing, supplier selection, purchasing, consolidation and export operations.", projectsTitle: <>From need to delivery.<br /><em>Real projects.</em></>, brandsTitle: <>Strong partnerships with<br /><em>technology manufacturers.</em></>, brandsText: "We bring innovative brands that help HVACR professionals work faster, safer and more accurately to the Türkiye market.", bdTitle: <>Your local partner for<br /><em>regional growth.</em></>, aboutTitle: <>Local knowledge.<br /><em>International reach.</em></>, contactTitle: <>Let’s develop the right<br /><em>opportunity together.</em></>, submit: "Send your inquiry",
  },
};

const businessAreas = [
  { no: "01", tr: ["HVACR DİSTRİBÜTÖRLÜĞÜ", "HVACR profesyonelleri için yenilikçi ekipmanlar.", "Profesyonel servis ekipmanları ile test ve ölçüm teknolojilerini Türkiye pazarıyla buluşturuyoruz.", "HVACR'ı keşfedin"], en: ["HVACR DISTRIBUTION", "Innovative tools for HVACR professionals.", "We bring professional service equipment and test and measurement technologies to the Türkiye market.", "Explore HVACR"], tone: "blue" },
  { no: "02", tr: ["ULUSLARARASI TİCARET VE PROJELER", "Ürün araştırmasından teslimata.", "Doğru üreticiden satın alma, konsolidasyon, ihracat ve proje teslimine kadar tüm süreci yönetiyoruz.", "Projeleri keşfedin"], en: ["INTERNATIONAL TRADE & PROJECTS", "From sourcing to delivery.", "We manage the entire process from the right supplier to purchasing, consolidation, export and project delivery.", "Explore Projects"], tone: "cobalt" },
  { no: "03", tr: ["KİMYASALLAR VE SOĞUTMA", "Soğutma sektörü için uzman çözümler.", "Vente Kimya ile soğutucu akışkan, kompresör yağı ve profesyonel kimyasal çözümler sunuyoruz.", "Vente Kimya'yı keşfedin"], en: ["CHEMICALS & REFRIGERATION", "Specialized solutions for refrigeration.", "Through Vente Kimya, we offer refrigerants, compressor oils and professional chemical solutions.", "Discover Vente Kimya"], tone: "cyan" },
  { no: "04", tr: ["ULUSLARARASI İŞ GELİŞTİRME", "Pazarlar kuruyor, ağlar geliştiriyoruz.", "Üreticiler için distribütör yapılanması, bayi geliştirme ve bölgesel satış yönetimi gerçekleştiriyoruz.", "İş geliştirme"], en: ["INTERNATIONAL BUSINESS DEVELOPMENT", "Building markets. Developing networks.", "We develop distributor structures, dealer networks and regional sales operations for manufacturers.", "Business Development"], tone: "navy" },
];
const tradeServices = [
  ["Ürün ve Üretici Araştırması", "Sourcing"], ["Merkezi Satın Alma", "Central Purchasing"], ["Tedarikçi Yönetimi", "Supplier Management"],
  ["Konsolidasyon", "Consolidation"], ["İhracat ve Lojistik", "Export & Logistics"], ["Anahtar Teslim Projeler", "Turnkey Projects"],
];
const projects = [
  { tr: ["Kamyon Kantar Sistemleri", "Afrika", "Kamyon kantarlarının ürün araştırması, üretim ve ihracat süreci."], en: ["Truck Weighing Systems", "Africa", "Sourcing, production and export of truck weighing systems."], image: "/project-truck-weighbridge.png" },
  { tr: ["Konteyner Ofisler", "Afrika", "Modüler konteyner ofislerin üretim ve teslimatı."], en: ["Container Offices", "Africa", "Production and delivery of modular container offices."], image: "/project-container-office.png" },
  { tr: ["Çelik Hangar Projesi", "Afrika", "Çelik konstrüksiyon hangar tedariği ve kurulumu."], en: ["Steel Hangar Project", "Africa", "Supply and installation of a steel construction hangar."], image: "/project-steel-hangar.png" },
  { tr: ["İş Kıyafeti Tedariği", "Afrika", "Kurumsal iş kıyafetlerinin üretim ve ihracatı."], en: ["Workwear Supply", "Africa", "Production and export of corporate workwear."], image: "/project-workwear.png" },
];
const brands = [["FIELDPIECE", "ABD", "USA", "Test ve Ölçüm", "Test & Measurement"], ["WIPCOOL", "Çin", "China", "HVACR Servis Ekipmanları", "HVACR Service Tools"], ["BLACK DIAMOND", "ABD", "USA", "Profesyonel El Aletleri", "Professional Tools"], ["SPECTROLINE", "ABD", "USA", "Kaçak Tespiti", "Leak Detection"], ["WEH", "Almanya", "Germany", "Bağlantı Teknolojileri", "Connection Technology"], ["MSA", "ABD", "USA", "Güvenlik Teknolojileri", "Safety Technology"], ["SUPERIOR ACCUTRAK", "ABD", "USA", "Ultrasonik Tespit", "Ultrasonic Detection"], ["ACCUTOOLS", "ABD", "USA", "Soğutucu Akışkan Ekipmanları", "Refrigerant Tools"], ["REFRIGERATION TECHNOLOGIES", "ABD", "USA", "HVACR Kimyasalları", "HVACR Chemicals"], ["TECNOSYSTEMI", "İtalya", "Italy", "HVAC Aksesuarları", "HVAC Accessories"]];
const bdServices = [["Pazara Giriş", "Market Entry"], ["Distribütör Arama ve Seçimi", "Distributor Search & Selection"], ["Distribütör Ağı Geliştirme", "Distributor Network Development"], ["Bayi Geliştirme", "Dealer Development"], ["Bölgesel Satış Yönetimi", "Regional Sales Management"], ["Ürün Lansmanı", "Product Launch"], ["Eğitim", "Training"], ["Fuarlar ve Yerel Pazarlama", "Exhibitions & Local Marketing"], ["Pazar İstihbaratı", "Market Intelligence"]];

export default function Home() {
  const [locale, setLocale] = useState<Locale>("tr"); const [menuOpen, setMenuOpen] = useState(false); const [heroSlide, setHeroSlide] = useState(0); const [brandOpen, setBrandOpen] = useState<number | null>(null); const [sent, setSent] = useState(false); const t = copy[locale]; const tr = locale === "tr";
  useEffect(() => { const timer = window.setInterval(() => setHeroSlide((slide) => (slide + 1) % heroSlides.length), 5600); return () => window.clearInterval(timer); }, []);
  useEffect(() => {
    if (new URLSearchParams(window.location.search).get("lang") === "en") setLocale("en");
  }, []);
  useEffect(() => {
    const openDetailFromHash = () => {
      if (window.location.hash === "#markalar") window.location.href = `/hvacr-ekipmanlari?lang=${locale}`;
      if (window.location.hash === "#projeler") window.location.href = `/uluslararasi-ticaret?lang=${locale}`;
    };
    window.addEventListener("hashchange", openDetailFromHash);
    return () => window.removeEventListener("hashchange", openDetailFromHash);
  }, [locale]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <main className="home-page">
    <nav className="nav" aria-label={tr ? "Ana navigasyon" : "Main navigation"}><a className="brand" href="#top" aria-label={tr ? "Vente ana sayfa" : "Vente home"}><img src="/vente-logo.jpg" alt="Vente" /></a><div className={`nav-links ${menuOpen ? "open" : ""}`}><a href="#hakkimizda">{t.nav[0]}</a><a href="#uzmanlik">{t.nav[1]}</a><a href="#markalar">{t.nav[2]}</a><a href="#projeler">{t.nav[3]}</a><a href="#insights">{t.nav[4]}</a><a href="#iletisim">{t.nav[5]}</a><div className="language-picker" role="group" aria-label={tr ? "Dil seçimi" : "Language selection"}><button className={tr ? "active" : ""} type="button" onClick={() => setLocale("tr")} aria-pressed={tr}>🇹🇷 <span>Türkçe</span></button><button className={!tr ? "active" : ""} type="button" onClick={() => setLocale("en")} aria-pressed={!tr}>🇬🇧 <span>English</span></button></div><a className="shop-link" href="https://www.ventecihaz.com" target="_blank" rel="noreferrer" data-track="online-shop">{tr ? "Online Mağaza" : "Online Shop"} ↗</a></div><button className="menu-button" type="button" aria-expanded={menuOpen} aria-label={tr ? "Menü" : "Menu"} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button></nav>
    <section className="hero hero-new" id="top"><div className="hero-media" aria-hidden="true">{heroSlides.map((image, index) => <img key={image} src={image} alt="" className={heroSlide === index ? "active" : ""} />)}<div className="hero-overlay" /></div><div className="hero-copy"><p className="eyebrow"><span /> {t.eyebrow}</p><h1>{t.hero}</h1><p className="hero-lead">{t.lead}</p><div className="hero-actions"><a className="primary-button" href="#hakkimizda">{t.discover} <span>↗</span></a><a className="text-link" href="#uzmanlik">{t.areas} <span>↓</span></a></div></div><div className="hero-pagination">{heroSlides.map((_, index) => <button key={index} className={heroSlide === index ? "active" : ""} onClick={() => setHeroSlide(index)} aria-label={`${index + 1}. görsel`} />)}</div></section>
    <section className="manifesto"><span>{tr ? "DOĞRU ÜRÜNÜ BULMAK." : "FINDING THE RIGHT PRODUCT."}</span><span>{tr ? "DOĞRU ORTAKLIĞI KURMAK." : "BUILDING THE RIGHT PARTNERSHIP."}</span><span>{tr ? "DOĞRU PAZARLA BULUŞTURMAK." : "CONNECTING IT WITH THE RIGHT MARKET."}</span></section>
    <section className="business" id="uzmanlik"><header className="section-head"><p className="eyebrow dark"><span /> {t.what}</p><h2>{t.whatTitle}</h2><p>{tr ? "İlgilendiğiniz iş kolunu seçerek özel detay sayfasını inceleyin." : "Choose a business area to explore its dedicated detail page."}</p></header><div className="business-grid">{businessAreas.map((area, index) => {const a=tr?area.tr:area.en;const routes=["/hvacr-ekipmanlari","/uluslararasi-ticaret","/vente-kimya","/is-gelistirme"];return <a className={`business-card ${area.tone}`} href={`${routes[index]}?lang=${locale}`} key={area.no}><div><span>{area.no}</span><small>{a[0]}</small></div><h3>{a[1]}</h3><p>{a[2]}</p><span className="business-card-action">{a[3]} <i>↗</i></span></a>})}</div></section>
    <section className="trade" id="area-02"><div className="trade-copy"><p className="eyebrow dark"><span /> {tr ? "ULUSLARARASI TİCARET VE PROJELER" : "INTERNATIONAL TRADE & PROJECTS"}</p><h2>{t.tradeTitle}</h2><p>{t.tradeText}</p><a className="primary-button" href="#iletisim">{tr ? "Proje başlatın" : "Start a project"} <span>↗</span></a></div><div className="service-list">{tradeServices.map((service, index) => <div key={service[1]}><span>{String(index + 1).padStart(2, "0")}</span><strong>{service[tr?0:1]}</strong><i>↗</i></div>)}</div></section>
    <section className="projects" id="projeler"><header className="section-head compact"><p className="eyebrow dark"><span /> {tr ? "PROJELER / REFERANSLAR" : "PROJECTS / REFERENCES"}</p><h2>{t.projectsTitle}</h2><p>{tr ? "Ürün araştırması, üretim, lojistik ve teslimat — tek ve bağlantılı bir süreç olarak yönetilir." : "Sourcing, production, logistics and delivery—managed as one connected process."}</p></header><div className="project-grid">{projects.map((project, index) => {const p=tr?project.tr:project.en;return <article className="project-card" key={project.en[0]}><div className="project-image"><img src={project.image} alt="" /><span>{String(index + 1).padStart(2, "0")}</span></div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[2]}</p><a href="#iletisim">{tr ? "Proje detayını inceleyin" : "View case study"} ↗</a></article>})}</div><p className="asset-note">{tr ? "Proje görselleri örnek yer tutuculardır; gerçek saha fotoğraflarıyla değiştirilmeye hazırdır." : "Project visuals are placeholders and ready to be replaced with actual field photography."}</p></section>
    <section className="chemicals" id="area-03"><div className="chemical-mark"><span>VENTE</span><strong>KİMYA</strong></div><div className="chemical-copy"><p className="eyebrow"><span /> {tr ? "KİMYASALLAR VE SOĞUTMA" : "CHEMICALS & REFRIGERATION"}</p><h2>{tr ? "HVACR Sektörü için Kimyasallar." : "Chemicals for the HVACR Industry."}</h2><p>{tr ? "Soğutma sektörüne yönelik uzman ürünleri, güvenilir tedarik yapısı ve teknik pazar bilgisiyle buluşturuyoruz." : "We combine specialist refrigeration products with a reliable supply structure and technical market expertise."}</p></div><div className="chemical-categories"><div><span>01</span><h3>{tr ? "Soğutucu Akışkanlar" : "Refrigerant Gases"}</h3><p>{tr ? "GeneralGas ürünlerinin Türkiye distribütörlüğü." : "Türkiye distribution of GeneralGas products."}</p></div><div><span>02</span><h3>{tr ? "Kompresör Yağları" : "Compressor Oils"}</h3><p>{tr ? "POE ve PAG kompresör yağları." : "POE and PAG compressor oils."}</p></div><div><span>03</span><h3>{tr ? "HVACR Kimyasalları" : "HVACR Chemicals"}</h3><p>{tr ? "Servis ve bakım için profesyonel çözümler." : "Professional solutions for service and maintenance."}</p></div></div></section>
    <section className="brands" id="markalar"><header className="section-head compact"><p className="eyebrow dark"><span /> {tr ? "HVACR DİSTRİBÜTÖRLÜĞÜ" : "HVACR DISTRIBUTION"}</p><h2>{t.brandsTitle}</h2><p>{t.brandsText}</p></header><div className="brand-grid">{brands.map((brand, index) => <button key={brand[0]} className={brandOpen === index ? "open" : ""} onClick={() => setBrandOpen(brandOpen === index ? null : index)}><strong>{brand[0]}</strong><span>{brand[tr?1:2]} · {brand[tr?3:4]}</span><i>{brandOpen === index ? "−" : "+"}</i>{brandOpen === index && <p>{tr ? "Profesyonel HVACR uygulamalarına yönelik yenilikçi çözümler. Ürünler ventecihaz.com üzerinden incelenebilir." : "Innovative solutions for professional HVACR applications. Products are available at ventecihaz.com."}</p>}</button>)}</div><a className="primary-button brands-cta" href="https://www.ventecihaz.com" target="_blank" rel="noreferrer" data-track="shop-products">{tr ? "Ürünleri ventecihaz.com’da inceleyin" : "Explore products at ventecihaz.com"} <span>↗</span></a></section>
    <section className="development" id="area-04"><div className="development-intro"><p className="eyebrow"><span /> {tr ? "ULUSLARARASI İŞ GELİŞTİRME" : "INTERNATIONAL BUSINESS DEVELOPMENT"}</p><h2>{t.bdTitle}</h2><p>{tr ? "Vente, uluslararası üreticilerin Türkiye, Doğu Avrupa ve Orta Doğu pazarlarındaki büyüme süreçlerinde satış ve kanal geliştirme partneri olarak görev alır." : "Vente serves as a sales and channel development partner for international manufacturers expanding across Türkiye, Eastern Europe and the Middle East."}</p></div><div className="bd-tags">{bdServices.map((item) => <span key={item[1]}>{item[tr?0:1]}</span>)}</div><article className="fieldpiece-case"><div><small>FIELDPIECE INSTRUMENTS</small><h3>{tr ? "Bölgesel İş Geliştirme" : "Regional Business Development"}</h3></div><p>{tr ? "Türkiye, Doğu Avrupa ve Orta Doğu bölgelerinde distribütör ve bayi yapılanması, kanal geliştirme ve yerel pazar faaliyetleri." : "Distributor and dealer structuring, channel development and local market activities across Türkiye, Eastern Europe and the Middle East."}</p><a href="#iletisim">{tr ? "Bölgesel partnerimiz olun" : "Become our regional partner"} ↗</a></article></section>
    <section className="about-new" id="hakkimizda"><div><p className="eyebrow dark"><span /> {tr ? "VENTE HAKKINDA" : "ABOUT VENTE"}</p><h2>{t.aboutTitle}</h2></div><div className="about-story"><p>{tr ? "Vente; dış ticaret tecrübesini, HVACR uzmanlığını ve uluslararası pazar bilgisini tek organizasyonda birleştirir." : "Vente combines international trade experience, HVACR expertise and global market knowledge within one organization."}</p><p>{tr ? "Doğru ürünü bulur, doğru ortaklığı kurar ve doğru pazarla buluştururuz." : "We find the right product, build the right partnership and connect it with the right market."}</p></div><div className="stats"><div><strong>2015</strong><span>{tr ? "Kuruluş" : "Founded"}</span></div><div><strong>10+</strong><span>{tr ? "Yıllık Deneyim" : "Years of Experience"}</span></div><div><strong>4</strong><span>{tr ? "Faaliyet Alanı" : "Business Areas"}</span></div><div><strong>10+</strong><span>{tr ? "Uluslararası Marka" : "International Brands"}</span></div></div></section>
    <section className="insights" id="insights"><p className="eyebrow dark"><span /> {tr ? "HABERLER VE İÇGÖRÜLER" : "NEWS & INSIGHTS"}</p><div className="insight-row"><article><small>{tr ? "PAZAR İÇGÖRÜSÜ" : "MARKET INSIGHT"}</small><h3>{tr ? "Yeni pazarlara girişte doğru distribütör yapısı" : "Building the right distributor structure for new markets"}</h3><a href="#iletisim">{tr ? "İçgörüyü okuyun" : "Read insight"} ↗</a></article><article><small>{tr ? "HVACR TEKNOLOJİSİ" : "HVACR TECHNOLOGY"}</small><h3>{tr ? "Profesyonel ölçüm teknolojilerinde dönüşüm" : "The transformation of professional measurement technology"}</h3><a href="#iletisim">{tr ? "İçgörüyü okuyun" : "Read insight"} ↗</a></article><article><small>{tr ? "PROJE GÜNCELLEMESİ" : "PROJECT UPDATE"}</small><h3>{tr ? "Afrika projelerinde merkezi satın alma modeli" : "Central purchasing model for projects in Africa"}</h3><a href="#iletisim">{tr ? "İçgörüyü okuyun" : "Read insight"} ↗</a></article></div></section>
    <section className="contact-new" id="iletisim"><div className="contact-intro"><p className="eyebrow dark"><span /> {tr ? "İŞ TALEBİ" : "BUSINESS INQUIRY"}</p><h2>{t.contactTitle}</h2><p>info@vente.com.tr<br />{tr ? "İstanbul, Türkiye" : "Istanbul, Türkiye"}</p></div><form onSubmit={submit}>{sent ? <div className="form-success"><span>✓</span><h3>{tr ? "Talebiniz alındı." : "We received your inquiry."}</h3><p>{tr ? "Ekibimiz en kısa sürede sizinle iletişime geçecek." : "Our team will contact you as soon as possible."}</p><button type="button" onClick={() => setSent(false)}>{tr ? "Yeni talep oluşturun" : "Create another inquiry"}</button></div> : <><fieldset><legend>{tr ? "Size nasıl yardımcı olabiliriz?" : "How can we help you?"}</legend><div className="inquiry-options">{(tr ? ["HVACR Ürünleri", "Bayi Olmak", "Uluslararası Ürün Araştırması", "Proje Talebi", "Vente Kimya", "Üretici / Pazara Giriş", "Diğer"] : ["HVACR Products", "Become a Dealer", "International Sourcing", "Project Inquiry", "Vente Kimya", "Manufacturer / Market Entry", "Other"]).map((option) => <label key={option}><input required type="radio" name="inquiry" value={option} /><span>{option}</span></label>)}</div></fieldset><div className="form-grid"><label>{tr ? "Ad Soyad" : "Name"}<input required name="name" /></label><label>{tr ? "Şirket" : "Company"}<input required name="company" /></label><label>{tr ? "Ülke" : "Country"}<select required name="country" defaultValue=""><option value="" disabled>{tr ? "Ülke seçin" : "Select country"}</option><option>Türkiye</option><option>{tr ? "Almanya" : "Germany"}</option><option>{tr ? "İtalya" : "Italy"}</option><option>{tr ? "Birleşik Krallık" : "United Kingdom"}</option><option>{tr ? "Birleşik Arap Emirlikleri" : "United Arab Emirates"}</option><option>{tr ? "Güney Afrika" : "South Africa"}</option><option>Nigeria</option><option>Ghana</option><option>{tr ? "Diğer" : "Other"}</option></select></label><label>{tr ? "E-posta" : "Email"}<input required type="email" name="email" /></label><label>{tr ? "Telefon" : "Phone"}<input type="tel" name="phone" /></label><label className="full">{tr ? "Mesaj" : "Message"}<textarea required name="message" rows={4} /></label></div><label className="consent"><input required type="checkbox" /> <span>{tr ? "KVKK kapsamında iletişim bilgilerimin işlenmesini kabul ediyorum." : "I consent to the processing of my contact information under GDPR."}</span></label><button className="form-submit" type="submit">{t.submit} <span>↗</span></button></>}</form></section>
    <footer><a className="brand footer-brand" href="#top"><img src="/vente-logo.jpg" alt="Vente" /></a><p>{tr ? "Ürünleri, üreticileri ve pazarları buluşturuyoruz." : "Connecting products, manufacturers and markets."}</p><div className="socials"><a href="https://www.linkedin.com/company/vente-technology-&-consulting-services" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://www.instagram.com/vente_tech/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.youtube.com/channel/UCuAt0fQvG1uaTE_OzNLWjsg" target="_blank" rel="noreferrer">YouTube ↗</a></div><small>© {new Date().getFullYear()} Vente Dış Ticaret Danışmanlık AŞ · KVKK · {tr ? "Gizlilik" : "Privacy"}</small></footer>
  </main>;
}
