"use client";

import { FormEvent, useEffect, useState } from "react";

type Locale = "tr" | "en";
const heroSlides = ["/slide-fieldpiece.jpg", "/slide-spin.jpg", "/slide-black-diamond.jpg", "/slide-spectroline.jpg"];

const copy = {
  tr: {
    nav: ["Vente", "Faaliyet Alanları", "Markalar", "Projeler", "İçgörüler", "İletişim"], eyebrow: "DIŞ TİCARET • DİSTRİBÜTÖRLÜK • İŞ GELİŞTİRME",
    hero: <>Ürünleri.<br />Üreticileri. <em>Pazarları.</em></>, lead: "Türkiye merkezli bir dış ticaret ve iş geliştirme şirketi olarak doğru ürünleri, güvenilir üreticileri ve yeni pazar fırsatlarını buluşturuyoruz.", discover: "Vente’yi keşfedin", areas: "Faaliyet alanlarımız", what: "NE YAPIYORUZ?", whatTitle: <>Tek yetkinlik.<br />Dört <em>iş alanı.</em></>, whatLead: "Ürün keşfinden dağıtıma, proje tedariğinden yeni pazar yapılanmasına kadar bütünsel ticari çözümler geliştiriyoruz.", tradeTitle: "İhtiyacı siz tanımlayın. Çözümü biz bulalım.", tradeText: "Başta Afrika olmak üzere farklı pazarlardaki müşterilerimiz için ürün araştırması, üretici seçimi, satın alma, konsolidasyon ve ihracat süreçlerini yönetiyoruz.", projectsTitle: <>İhtiyaçtan teslimata.<br /><em>Gerçek projeler.</em></>, brandsTitle: <>Teknoloji üreticileriyle<br /><em>güçlü ortaklıklar.</em></>, brandsText: "HVACR profesyonellerinin işlerini daha hızlı, doğru ve güvenli yapmalarını sağlayan yenilikçi markaları Türkiye pazarıyla buluşturuyoruz.", bdTitle: <>Bölgesel büyüme için<br /><em>yerel partneriniz.</em></>, aboutTitle: <>Yerel bilgi.<br /><em>Uluslararası erişim.</em></>, contactTitle: <>Doğru fırsatı<br /><em>birlikte geliştirelim.</em></>, submit: "Talebinizi gönderin",
  },
  en: {
    nav: ["Vente", "Business Areas", "Brands", "Projects", "Insights", "Contact"], eyebrow: "INTERNATIONAL TRADE • DISTRIBUTION • BUSINESS DEVELOPMENT",
    hero: <>Connecting Products.<br />Markets. <em>Opportunities.</em></>, lead: "Vente is a Türkiye-based international trade and business development company connecting innovative manufacturers, products and markets.", discover: "Discover Vente", areas: "Our business areas", what: "WHAT WE DO", whatTitle: <>One capability.<br />Four <em>business areas.</em></>, whatLead: "From product discovery and distribution to project supply and market development, we build integrated commercial solutions.", tradeTitle: "You define the need. We find the solution.", tradeText: "For clients across Africa and other international markets, we manage sourcing, supplier selection, purchasing, consolidation and export operations.", projectsTitle: <>From need to delivery.<br /><em>Real projects.</em></>, brandsTitle: <>Strong partnerships with<br /><em>technology manufacturers.</em></>, brandsText: "We bring innovative brands that help HVACR professionals work faster, safer and more accurately to the Türkiye market.", bdTitle: <>Your local partner for<br /><em>regional growth.</em></>, aboutTitle: <>Local knowledge.<br /><em>International reach.</em></>, contactTitle: <>Let’s develop the right<br /><em>opportunity together.</em></>, submit: "Send your inquiry",
  },
};

const businessAreas = [
  { no: "01", tag: "HVACR DISTRIBUTION", title: "Innovative tools for HVACR professionals.", text: "Profesyonel servis ekipmanları ile test ve ölçüm teknolojilerini Türkiye pazarıyla buluşturuyoruz.", action: "Explore HVACR", tone: "blue" },
  { no: "02", tag: "INTERNATIONAL TRADE & PROJECTS", title: "From sourcing to delivery.", text: "Doğru üreticiden satın alma, konsolidasyon, ihracat ve proje teslimine kadar tüm süreci yönetiyoruz.", action: "Explore Projects", tone: "cobalt" },
  { no: "03", tag: "CHEMICALS & REFRIGERATION", title: "Specialized solutions for refrigeration.", text: "Vente Kimya ile soğutucu akışkan, kompresör yağı ve profesyonel kimyasal çözümler sunuyoruz.", action: "Discover Vente Kimya", tone: "cyan" },
  { no: "04", tag: "BUSINESS DEVELOPMENT", title: "Building markets. Developing networks.", text: "Üreticiler için distribütör yapılanması, bayi geliştirme ve bölgesel satış yönetimi gerçekleştiriyoruz.", action: "Business Development", tone: "navy" },
];
const tradeServices = ["Sourcing", "Central Purchasing", "Supplier Management", "Consolidation", "Export & Logistics", "Turnkey Projects"];
const projects = [
  { title: "Truck Weighing Systems", region: "Africa", image: "/slide-black-diamond.jpg", text: "Kamyon kantarlarının sourcing, üretim ve ihracat süreci." },
  { title: "Container Offices", region: "Africa", image: "/slide-fieldpiece.jpg", text: "Modüler konteyner ofislerin üretim ve teslimatı." },
  { title: "Steel Hangar Project", region: "Africa", image: "/slide-spin.jpg", text: "Çelik konstrüksiyon hangar tedariği ve kurulumu." },
  { title: "Workwear Supply", region: "Africa", image: "/slide-spectroline.jpg", text: "Kurumsal iş kıyafetlerinin üretim ve ihracatı." },
];
const brands = [["FIELDPIECE", "USA", "Test & Measurement"], ["WIPCOOL", "China", "HVACR Service Tools"], ["BLACK DIAMOND", "USA", "Professional Tools"], ["SPECTROLINE", "USA", "Leak Detection"], ["WEH", "Germany", "Connection Technology"], ["MSA", "USA", "Safety Technology"], ["SUPERIOR ACCUTRAK", "USA", "Ultrasonic Detection"], ["ACCUTOOLS", "USA", "Refrigerant Tools"], ["REFRIGERATION TECHNOLOGIES", "USA", "HVACR Chemicals"], ["TECNOSYSTEMI", "Italy", "HVAC Accessories"]];
const bdServices = ["Market Entry", "Distributor Search & Selection", "Distributor Network Development", "Dealer Development", "Regional Sales Management", "Product Launch", "Training", "Exhibitions & Local Marketing", "Market Intelligence"];

export default function Home() {
  const [locale, setLocale] = useState<Locale>("tr"); const [menuOpen, setMenuOpen] = useState(false); const [heroSlide, setHeroSlide] = useState(0); const [brandOpen, setBrandOpen] = useState<number | null>(null); const [sent, setSent] = useState(false); const t = copy[locale];
  useEffect(() => { const timer = window.setInterval(() => setHeroSlide((slide) => (slide + 1) % heroSlides.length), 5600); return () => window.clearInterval(timer); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); };
  return <main>
    <nav className="nav" aria-label="Ana navigasyon"><a className="brand" href="#top" aria-label="Vente ana sayfa"><img src="/vente-logo.jpg" alt="Vente" /></a><div className={`nav-links ${menuOpen ? "open" : ""}`}><a href="#hakkimizda">{t.nav[0]}</a><a href="#uzmanlik">{t.nav[1]}</a><a href="#markalar">{t.nav[2]}</a><a href="#projeler">{t.nav[3]}</a><a href="#insights">{t.nav[4]}</a><a href="#iletisim">{t.nav[5]}</a><button className="lang-switch" type="button" onClick={() => setLocale(locale === "tr" ? "en" : "tr")}>{locale === "tr" ? "EN" : "TR"}</button><a className="shop-link" href="https://www.ventecihaz.com" target="_blank" rel="noreferrer" data-track="online-shop">Online Shop ↗</a></div><button className="menu-button" type="button" aria-expanded={menuOpen} aria-label="Menü" onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button></nav>
    <section className="hero hero-new" id="top"><div className="hero-media" aria-hidden="true">{heroSlides.map((image, index) => <img key={image} src={image} alt="" className={heroSlide === index ? "active" : ""} />)}<div className="hero-overlay" /></div><div className="hero-copy"><p className="eyebrow"><span /> {t.eyebrow}</p><h1>{t.hero}</h1><p className="hero-lead">{t.lead}</p><div className="hero-actions"><a className="primary-button" href="#hakkimizda">{t.discover} <span>↗</span></a><a className="text-link" href="#uzmanlik">{t.areas} <span>↓</span></a></div></div><div className="hero-pagination">{heroSlides.map((_, index) => <button key={index} className={heroSlide === index ? "active" : ""} onClick={() => setHeroSlide(index)} aria-label={`${index + 1}. görsel`} />)}</div></section>
    <section className="manifesto"><span>FINDING THE RIGHT PRODUCT.</span><span>BUILDING THE RIGHT PARTNERSHIP.</span><span>CONNECTING IT WITH THE RIGHT MARKET.</span></section>
    <section className="business" id="uzmanlik"><header className="section-head"><p className="eyebrow dark"><span /> {t.what}</p><h2>{t.whatTitle}</h2><p>{t.whatLead}</p></header><div className="business-grid">{businessAreas.map((area) => <article className={`business-card ${area.tone}`} key={area.no}><div><span>{area.no}</span><small>{area.tag}</small></div><h3>{area.title}</h3><p>{area.text}</p><a href={`#area-${area.no}`}>{area.action} <span>↗</span></a></article>)}</div></section>
    <section className="trade" id="area-02"><div className="trade-copy"><p className="eyebrow dark"><span /> INTERNATIONAL TRADE & PROJECTS</p><h2>{t.tradeTitle}</h2><p>{t.tradeText}</p><a className="primary-button" href="#iletisim">Start a project <span>↗</span></a></div><div className="service-list">{tradeServices.map((service, index) => <div key={service}><span>{String(index + 1).padStart(2, "0")}</span><strong>{service}</strong><i>↗</i></div>)}</div></section>
    <section className="projects" id="projeler"><header className="section-head compact"><p className="eyebrow dark"><span /> PROJECTS / REFERENCES</p><h2>{t.projectsTitle}</h2><p>Sourcing, production, logistics and delivery—managed as one connected process.</p></header><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.title}><div className="project-image"><img src={project.image} alt="" /><span>{String(index + 1).padStart(2, "0")}</span></div><small>{project.region}</small><h3>{project.title}</h3><p>{project.text}</p><a href="#iletisim">View case study ↗</a></article>)}</div><p className="asset-note">Proje görselleri örnek yer tutuculardır; gerçek saha fotoğraflarıyla değiştirilmeye hazırdır.</p></section>
    <section className="chemicals" id="area-03"><div className="chemical-mark"><span>VENTE</span><strong>KİMYA</strong></div><div className="chemical-copy"><p className="eyebrow"><span /> CHEMICALS & REFRIGERATION</p><h2>Chemicals for the HVACR Industry.</h2><p>Soğutma sektörüne yönelik uzman ürünleri, güvenilir tedarik yapısı ve teknik pazar bilgisiyle buluşturuyoruz.</p></div><div className="chemical-categories"><div><span>01</span><h3>Refrigerant Gases</h3><p>GeneralGas ürünlerinin Türkiye distribütörlüğü.</p></div><div><span>02</span><h3>Compressor Oils</h3><p>POE ve PAG kompresör yağları.</p></div><div><span>03</span><h3>HVACR Chemicals</h3><p>Servis ve bakım için profesyonel çözümler.</p></div></div></section>
    <section className="brands" id="markalar"><header className="section-head compact"><p className="eyebrow dark"><span /> HVACR DISTRIBUTION</p><h2>{t.brandsTitle}</h2><p>{t.brandsText}</p></header><div className="brand-grid">{brands.map((brand, index) => <button key={brand[0]} className={brandOpen === index ? "open" : ""} onClick={() => setBrandOpen(brandOpen === index ? null : index)}><strong>{brand[0]}</strong><span>{brand[1]} · {brand[2]}</span><i>{brandOpen === index ? "−" : "+"}</i>{brandOpen === index && <p>Profesyonel HVACR uygulamalarına yönelik yenilikçi çözümler. Ürünler ventecihaz.com üzerinden incelenebilir.</p>}</button>)}</div><a className="primary-button brands-cta" href="https://www.ventecihaz.com" target="_blank" rel="noreferrer" data-track="shop-products">Ürünleri ventecihaz.com’da inceleyin <span>↗</span></a></section>
    <section className="development" id="area-04"><div className="development-intro"><p className="eyebrow"><span /> INTERNATIONAL BUSINESS DEVELOPMENT</p><h2>{t.bdTitle}</h2><p>Vente, uluslararası üreticilerin Türkiye, Doğu Avrupa ve Orta Doğu pazarlarındaki büyüme süreçlerinde satış ve kanal geliştirme partneri olarak görev alır.</p></div><div className="bd-tags">{bdServices.map((item) => <span key={item}>{item}</span>)}</div><article className="fieldpiece-case"><div><small>FIELDPIECE INSTRUMENTS</small><h3>Regional Business Development</h3></div><p>Türkiye, Doğu Avrupa ve Orta Doğu bölgelerinde distribütör ve bayi yapılanması, kanal geliştirme ve yerel pazar faaliyetleri.</p><a href="#iletisim">Become our regional partner ↗</a></article></section>
    <section className="about-new" id="hakkimizda"><div><p className="eyebrow dark"><span /> ABOUT VENTE</p><h2>{t.aboutTitle}</h2></div><div className="about-story"><p>Vente; dış ticaret tecrübesini, HVACR uzmanlığını ve uluslararası pazar bilgisini tek organizasyonda birleştirir.</p><p>Doğru ürünü bulur, doğru ortaklığı kurar ve doğru pazarla buluştururuz.</p></div><div className="stats"><div><strong>2015</strong><span>Founded</span></div><div><strong>10+</strong><span>Years of Experience</span></div><div><strong>4</strong><span>Business Areas</span></div><div><strong>10+</strong><span>International Brands</span></div></div></section>
    <section className="insights" id="insights"><p className="eyebrow dark"><span /> NEWS & INSIGHTS</p><div className="insight-row"><article><small>MARKET INSIGHT</small><h3>Yeni pazarlara girişte doğru distribütör yapısı</h3><a href="#iletisim">Read insight ↗</a></article><article><small>HVACR TECHNOLOGY</small><h3>Profesyonel ölçüm teknolojilerinde dönüşüm</h3><a href="#iletisim">Read insight ↗</a></article><article><small>PROJECT UPDATE</small><h3>Afrika projelerinde merkezi satın alma modeli</h3><a href="#iletisim">Read insight ↗</a></article></div></section>
    <section className="contact-new" id="iletisim"><div className="contact-intro"><p className="eyebrow dark"><span /> BUSINESS INQUIRY</p><h2>{t.contactTitle}</h2><p>info@vente.com.tr<br />İstanbul, Türkiye</p></div><form onSubmit={submit}>{sent ? <div className="form-success"><span>✓</span><h3>Talebiniz alındı.</h3><p>Ekibimiz en kısa sürede sizinle iletişime geçecek.</p><button type="button" onClick={() => setSent(false)}>Yeni talep oluşturun</button></div> : <><fieldset><legend>How can we help you?</legend><div className="inquiry-options">{["HVACR Products", "Become a Dealer", "International Sourcing", "Project Inquiry", "Vente Kimya", "Manufacturer / Market Entry", "Other"].map((option) => <label key={option}><input required type="radio" name="inquiry" value={option} /><span>{option}</span></label>)}</div></fieldset><div className="form-grid"><label>Name<input required name="name" /></label><label>Company<input required name="company" /></label><label>Country<select required name="country" defaultValue=""><option value="" disabled>Select country</option><option>Türkiye</option><option>Germany</option><option>Italy</option><option>United Kingdom</option><option>United Arab Emirates</option><option>South Africa</option><option>Nigeria</option><option>Ghana</option><option>Other</option></select></label><label>Email<input required type="email" name="email" /></label><label>Phone<input type="tel" name="phone" /></label><label className="full">Message<textarea required name="message" rows={4} /></label></div><label className="consent"><input required type="checkbox" /> <span>KVKK / GDPR kapsamında iletişim bilgilerimin işlenmesini kabul ediyorum.</span></label><button className="form-submit" type="submit">{t.submit} <span>↗</span></button></>}</form></section>
    <footer><a className="brand footer-brand" href="#top"><img src="/vente-logo.jpg" alt="Vente" /></a><p>Connecting products, manufacturers and markets.</p><div className="socials"><a href="https://www.linkedin.com/company/vente-technology-&-consulting-services" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="https://www.instagram.com/vente_tech/" target="_blank" rel="noreferrer">Instagram ↗</a><a href="https://www.youtube.com/channel/UCuAt0fQvG1uaTE_OzNLWjsg" target="_blank" rel="noreferrer">YouTube ↗</a></div><small>© {new Date().getFullYear()} Vente Dış Ticaret Danışmanlık AŞ · KVKK · Privacy</small></footer>
  </main>;
}
